version: "3.3"
services:
  localdb:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    env_file:
      - ./.env

  testdb:
    image: postgres:14
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    env_file:
      - ./.env
