version: "3.3"
services:
  localdb:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localenv
      - POSTGRES_DATABASE=postgres

  testdb:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localenv
      - POSTGRES_DATABASE=postgres
