export const UNIQUE_CONSTRAINT_ERROR_CODE = '23505';
export const SALT_SEPARATOR = ':';
export const PASSWORD_MIN_LENGTH = 6;
export const INTERNAL_SERVER_ERROR_CODE = 500;
export const BAD_REQUEST_ERROR_CODE = 400;
export const UNAUTHORIZED_ERROR_CODE = 401;
